on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./scripts/lint.sh
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./scripts/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nginx
          path: bin
  analyse:
    runs-on: ubuntu-latest
    name: Analyse
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nginx
          path: bin
      - name: Analyse
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./scripts/analyse.sh
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nginx
          path: bin
      - name: Test
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./scripts/test.sh
  tag:
    runs-on: ubuntu-latest
    name: Tag
    needs: test
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && (success() || failure()) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check semver bump
        id: check-semver
        run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ [^/]+/patch/.+$ ]]; then
            echo ::set-output name=semver::patch
          elif [[ "${{ github.event.head_commit.message }}" =~ ^Merge\ pull\ request\ #[0-9]+\ from\ [^/]+/major/.+$ ]]; then
            echo ::set-output name=semver::major
          else
            echo ::set-output name=semver::minor
          fi
      - name: Bump major version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'major' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: major
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump minor version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'minor' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump patch version and push tag
        if: ${{ steps.check-semver.outputs.semver == 'patch' }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
