on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./build.sh
      - name: Test
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./test.sh
      - name: LeakCheck
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./leakcheck.sh
  tag:
    runs-on: ubuntu-latest
    name: Tag
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Bump major version and push tag
        if: ${{ startsWith(github.head_ref, 'refs/heads/major/') }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: major
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump minor version and push tag
        if: ${{ startsWith(github.head_ref, 'refs/heads/minor/') }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump patch version and push tag
        if: ${{ startsWith(github.head_ref, 'refs/heads/patch/') }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        if: ${{ !(startsWith(github.head_ref, 'refs/heads/major/') || startsWith(github.head_ref, 'refs/heads/minor/') || startsWith(github.head_ref, 'refs/heads/patch/')) }}
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
