on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Build
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./build.sh
      - name: Test
        uses: ./.github/actions/nginx-module-toolbox
        with:
          entrypoint: ./test.sh
