on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        if: ${{ startsWith(github.ref, 'refs/heads/patch/') }}
        run: echo hi guy
      # - name: Build
      #   uses: ./.github/actions/nginx-module-toolbox
      #   with:
      #     entrypoint: ./build.sh
      # - name: Test
      #   uses: ./.github/actions/nginx-module-toolbox
      #   with:
      #     entrypoint: ./test.sh
      # - name: Bump major version and push tag
      #   if: ${{ github.ref == 'master' && startsWith(github.head_ref, 'major/') }}
      #   uses: anothrNick/github-tag-action@1.17.2
      #   env:
      #     DEFAULT_BUMP: major
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Bump minor version and push tag
      #   if: ${{ github.ref == 'master' && startsWith(github.head_ref, 'minor/') }}
      #   uses: anothrNick/github-tag-action@1.17.2
      #   env:
      #     DEFAULT_BUMP: minor
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Bump patch version and push tag
      #   if: ${{ github.ref == 'master' && startsWith(github.head_ref, 'patch/') }}
      #   uses: anothrNick/github-tag-action@1.17.2
      #   env:
      #     DEFAULT_BUMP: patch
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Bump version and push tag
      #   if: ${{ github.ref == 'master' && !(startsWith(github.head_ref, 'major/') || startsWith(github.head_ref, 'minor/') || startsWith(github.head_ref, 'patch/')) }}
      #   uses: anothrNick/github-tag-action@1.17.2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
