name: Nginx CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [linux]
    container: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: ./build.sh
  test:
    runs-on: [linux]
    container: Dockerfile
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Test::Nginx
        run: ./test.sh
